title = "Catherine Blatter"
baseurl = " "
relativeurls = false
languageCode = "en-us"
theme = "hyde"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$", "_data/.*"]


 [permalinks]
    post = "blog/:year/:month/:day/:slug/"
    blog = "blog/:year/:month/:day/:slug/"
    
[[menu.main]]
    name = "Blog"
    weight = 1
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "About"
    weight = -1
    url = "/about/"
# [[menu.main]]
#    name = "Projects"
#    weight = 2
#    url = "/project/"
#[[menu.main]]
#    name = "Photos"
#    weight = 4
#    url = "/categories/photos/"
#[[menu.contact]]
#   name = "Email"
#    weight = 3
#    url = "mailto:catherine.blatter@gmail.com"
[[menu.contact]]
    name = "GitHub"
    weight = 2
    url = "https://github.com/cathblatter"
[[menu.contact]]
    name = "Twitter"
    weight = 1
    url = "https://twitter.com/cathblatter"
    
[author]
    image = "images/catherine.png"

    
[params]
    description = "RN | cand. MSc | #rstats | likes bikes, data & the nordic outdoors 🇳🇴🇸🇪🇮🇸"
    EnableEmoji = true
    contactHeader = "Links"
    n_posts_front = 5
    show_projects_front = true
    n_projects_front = 5
    
    # hyde
    themeColor = "base16-solarized-cath"
    customCss = ["css/hamburgers.css", "css/custom.css"]
    
    # options for highlight.js (version, additional languages, and theme)
    # import minified languages to /js/highlight.js/{version}/languages
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "/js"
    highlightjsLang = ["r", "yaml", "bash", "tex", "sql", "markdown"]
    highlightjsTheme = "github"

    MathJaxCDN = "https://cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
