---
title: Useful hints for Endnote
author: ~
date: '2019-02-16'
slug: useful-hints
type: blog
categories: []
tags: []
Categories:
  - Endnote
Description: ''
Tags:
  - hint
menu: []
---

## `r emo::ji("bulb")` A collection of hints for working with Endnote

*this is a working document primarily addressed at students from the Institute of*
*Nursing Science at University of Basel and may change over time - feedback welcome*

This post was last updated on `r format(Sys.Date(), "%Y-%m-%d")`


### What is this document and why?

Endnote is the citation manager proclaimed in many courses at the INS. Over the past years 
I've encountered a number of struggles personally or through my peers. This document lists 
the major problems I've seen and offers solutions that worked for me. If you have any 
comments please contact me. 

#### Question: Endnote does not find/download articles with full-text search?

Answer: The most obvious reason might be your license. According to asknet.unibas.ch 
you need to renew it every year at little cost (especially, if you do it in January/February). It may not be 
obvious as Endnote keeps working even without the License - but major advantages such as full-text-search are not 
available.  

1. Check if you have an valid licensed version of Endnote? ( You can do so in your asknet [dot] unibas [dot] ch-account)  
2. Probably check if you need to update your version? (Endnote -> Check for updates)  

The second problem might be lack of a so called "connection", for instance for the Wiley Online Library. This 
means that Endnote cannot access papers of this specific journal or publishing company. No problem, you 
can find and install from endnote.com. Instruction are posted here: https://endnote.com/downloads/connection-files/ 

#### Q: Journal names are not displayed in full (according to APA style)

You need to import/update your terms list for every new .enl-library you create.  

*EndNote -> Tools -> Open Term Lists -> Journals Term List* change to Lists, 
*Import Lists*, go to *Applications-> Endnote -> Terms -> Medical.txt* and choose this file.  

Endnote has now imported all styles and once you close and re-open your library, it should work.  


#### Q: The Author names are abbreviated altough they should not?


... (will follow)